#!/usr/bin/env bash 

#while true
#do

if [[ $(xrandr -d :0 -q | grep ' connected' | wc -l) = "2" ]]; then

xrandr --output eDP1 --mode 1920x1080 --pos 0x128 --rotate normal --output DP1 --off --output DP1-1 --off --output DP1-2 --primary --mode 1920x1200 --pos 1920x0 --rotate normal --output DP1-3 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off

else

xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output DP1-1 --off --output DP1-2 --off --output DP1-3 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off

fi
#sleep 3
#done